export default defineAppConfig({
  pages: [
    'pages/css-token/typography/index',
    'pages/css-token/color/index',
    'pages/css-token/radii/index',
    'pages/css-token/spacing/index',
    'pages/button/index',
    'pages/button-flush/index',
    'pages/button-griditem/index',
    'pages/button-text-button/index',
    'pages/button-fab/index',
    'pages/form-display/index',
    'pages/form-input/index',
    'pages/form-action/index',
    'pages/tag/index',
    'pages/input/index',
    'pages/card/index',
    'pages/icon/index',
    'pages/modal/index',
  ],
  window: {
    navigationBarTitleText: 'FDesign System',
    navigationBarBackgroundColor: '#FFFFFF',
    navigationBarTextStyle: 'black',
    backgroundColor: '#FAFAFA',
  },
});
