export const referenceColors = {
  brand: {
    blue: {
      1: '#f2f6ff',
      2: '#e5edff',
      3: '#ccdbff',
      4: '#b2caff',
      5: '#99b8ff',
      6: '#80a6ff',
      7: '#6694ff',
      8: '#4d83ff',
      9: '#3371ff',
    },
    pink: {
      1: '#fff2f6',
      2: '#ffe5ed',
      3: '#ffccdb',
      4: '#ffb2c9',
      5: '#ff99b7',
      6: '#ff80a6',
      7: '#ff6694',
      8: '#ff4d82',
      9: '#ff3371',
    },
  },
  functional: {
    red: {
      1: '#ffd9dc',
      2: '#ffccd0',
      3: '#ffb2b9',
      4: '#ffa6ad',
      5: '#ff99a2',
      6: '#f27984',
      7: '#e55c68',
      8: '#e53948',
      9: '#d92c3a',
    },
    orange: {
      1: '#ffecd9',
      2: '#ffe1bf',
      3: '#fed4a5',
      4: '#ffc78c',
      5: '#ffc180',
      6: '#ffb566',
      7: '#ffa94d',
      8: '#ff9d33',
      9: '#ff8a0e',
    },
    green: {
      1: '#cef2e0',
      2: '#c2f2d9',
      3: '#ace5c8',
      4: '#8dd9b2',
      5: '#82d9ac',
      6: '#52cc8d',
      7: '#3fc27f',
      8: '#26bf71',
      9: '#0cba60',
    },
  },
  neutral: {
    gray: {
      1: '#050c1c',
      2: '#1e2533',
      3: '#81858d',
      4: '#9c9ea4',
      5: '#b4b6bc',
      6: '#f3f4f5',
      '2a60': '#787c85',
      '2a40': '#a4a8ac',
      '2a20': '#d2d3d6',
    },
    white: {
      1: '#ffffff',
      2: 'rgba(255, 255, 255, 0.8)',
      3: 'rgba(255, 255, 255, 0.6)',
      4: 'rgba(255, 255, 255, 0.4)',
      5: 'rgba(255, 255, 255, 0.3)',
      6: 'rgba(255, 255, 255, 0.2)',
    },
  },
} as const;

const neutralText = {
  primary: referenceColors.neutral.gray[2],
  secondary: referenceColors.neutral.gray['2a60'],
  tertiary: referenceColors.neutral.gray['2a40'],
  disabled: referenceColors.neutral.gray['2a20'],
  inversePrimary: referenceColors.neutral.white[1],
  inverseSecondary: referenceColors.neutral.white[3],
  inverseTertiary: referenceColors.neutral.white[4],
} as const;

export const semanticColors = {
  text: neutralText,
  tag: {
    blue: {
      fillPrimaryBackground: referenceColors.brand.blue[8],
      fillPrimaryForeground: referenceColors.neutral.white[1],
      fillSecondaryBackground: referenceColors.brand.blue[1],
      fillSecondaryForeground: referenceColors.brand.blue[8],
      outlineBorder: referenceColors.brand.blue[3],
      outlineForeground: referenceColors.brand.blue[8],
      outlineDivider: referenceColors.brand.blue[3],
    },
    pink: {
      fillPrimaryBackground: referenceColors.brand.pink[8],
      fillPrimaryForeground: referenceColors.neutral.white[1],
      fillSecondaryBackground: referenceColors.brand.pink[1],
      fillSecondaryForeground: referenceColors.brand.pink[8],
      outlineBorder: referenceColors.brand.pink[3],
      outlineForeground: referenceColors.brand.pink[8],
      outlineDivider: referenceColors.brand.pink[3],
    },
    red: {
      fillPrimaryBackground: referenceColors.functional.red[8],
      fillPrimaryForeground: referenceColors.neutral.white[1],
      fillSecondaryBackground: referenceColors.functional.red[1],
      fillSecondaryForeground: referenceColors.functional.red[8],
      outlineBorder: referenceColors.functional.red[3],
      outlineForeground: referenceColors.functional.red[8],
      outlineDivider: referenceColors.functional.red[3],
    },
    yellow: {
      fillPrimaryBackground: referenceColors.functional.orange[8],
      fillPrimaryForeground: referenceColors.neutral.white[1],
      fillSecondaryBackground: referenceColors.functional.orange[1],
      fillSecondaryForeground: referenceColors.functional.orange[8],
      outlineBorder: referenceColors.functional.orange[3],
      outlineForeground: referenceColors.functional.orange[8],
      outlineDivider: referenceColors.functional.orange[3],
    },
    green: {
      fillPrimaryBackground: referenceColors.functional.green[8],
      fillPrimaryForeground: referenceColors.neutral.white[1],
      fillSecondaryBackground: referenceColors.functional.green[1],
      fillSecondaryForeground: referenceColors.functional.green[8],
      outlineBorder: referenceColors.functional.green[3],
      outlineForeground: referenceColors.functional.green[8],
      outlineDivider: referenceColors.functional.green[3],
    },
    purple: {
      fillPrimaryBackground: '#884cff',
      fillPrimaryForeground: referenceColors.neutral.white[1],
      fillSecondaryBackground: '#f3edff',
      fillSecondaryForeground: '#884cff',
      outlineBorder: '#d9c7ff',
      outlineForeground: '#884cff',
      outlineDivider: '#d9c7ff',
    },
    grey: {
      fillPrimaryBackground: referenceColors.neutral.gray[6],
      fillPrimaryForeground: referenceColors.neutral.white[1],
      fillSecondaryBackground: referenceColors.neutral.gray[6],
      fillSecondaryForeground: referenceColors.neutral.white[1],
      outlineBorder: '#ededee',
      outlineForeground: referenceColors.neutral.gray['2a60'],
      outlineDivider: '#ededee',
    },
  },
  surface: {
    page: '#f5f7fa',
    base: referenceColors.neutral.white[1],
    muted: referenceColors.neutral.gray[6],
    overlay: 'rgba(0, 0, 0, 0.8)',
    overlaySoft: 'rgba(0, 0, 0, 0.7)',
    footer: '#cbd2e1',
  },
  border: {
    subtle: '#ededee',
    strong: referenceColors.neutral.gray['2a20'],
    inverse: referenceColors.neutral.white[1],
  },
  icon: {
    primary: referenceColors.neutral.gray[2],
    inverse: referenceColors.neutral.white[1],
  },
  external: {
    alipay: '#049fff',
    wechat: '#51d768',
  },
  data: {
    up: referenceColors.functional.red[8],
    down: referenceColors.functional.green[8],
  },
  action: {
    primary: {
      background: referenceColors.brand.blue[8],
      backgroundHover: referenceColors.brand.blue[7],
      backgroundActive: referenceColors.brand.blue[9],
      border: referenceColors.brand.blue[8],
      borderHover: referenceColors.brand.blue[7],
      borderActive: referenceColors.brand.blue[9],
      foreground: referenceColors.neutral.white[1],
      outlineForeground: referenceColors.brand.blue[8],
      subtleBackground: referenceColors.brand.blue[1],
      subtleBorder: referenceColors.brand.blue[3],
      subtleForeground: referenceColors.brand.blue[8],
      inactiveBackground: referenceColors.brand.blue[4],
      inactiveBorder: referenceColors.brand.blue[4],
      inactiveForeground: referenceColors.brand.blue[4],
      disabled: referenceColors.neutral.gray[6],
    },
    success: {
      background: referenceColors.functional.green[8],
      backgroundHover: referenceColors.functional.green[7],
      backgroundActive: referenceColors.functional.green[9],
      border: referenceColors.functional.green[8],
      borderHover: referenceColors.functional.green[7],
      borderActive: referenceColors.functional.green[9],
      foreground: referenceColors.neutral.white[1],
      subtleBackground: referenceColors.functional.green[1],
      subtleBorder: referenceColors.functional.green[3],
      subtleForeground: referenceColors.functional.green[8],
      disabled: referenceColors.neutral.gray[6],
    },
    warning: {
      background: referenceColors.functional.orange[8],
      backgroundHover: referenceColors.functional.orange[7],
      backgroundActive: referenceColors.functional.orange[9],
      border: referenceColors.functional.orange[8],
      borderHover: referenceColors.functional.orange[7],
      borderActive: referenceColors.functional.orange[9],
      foreground: referenceColors.neutral.gray[2],
      subtleBackground: referenceColors.functional.orange[1],
      subtleBorder: referenceColors.functional.orange[3],
      subtleForeground: referenceColors.functional.orange[8],
      disabled: referenceColors.neutral.gray[6],
    },
    danger: {
      background: referenceColors.functional.red[8],
      backgroundHover: referenceColors.functional.red[7],
      backgroundActive: referenceColors.functional.red[9],
      border: referenceColors.functional.red[8],
      borderHover: referenceColors.functional.red[7],
      borderActive: referenceColors.functional.red[9],
      foreground: referenceColors.neutral.white[1],
      subtleBackground: referenceColors.functional.red[1],
      subtleBorder: referenceColors.functional.red[3],
      subtleForeground: referenceColors.functional.red[8],
      disabled: referenceColors.neutral.gray[6],
    },
    neutral: {
      background: referenceColors.neutral.white[1],
      backgroundHover: referenceColors.neutral.gray[6],
      backgroundActive: referenceColors.neutral.gray['2a20'],
      border: '#ededee',
      borderHover: referenceColors.neutral.gray[4],
      borderActive: referenceColors.neutral.gray[3],
      foreground: referenceColors.neutral.gray[2],
      subtleBackground: referenceColors.neutral.gray[6],
      subtleBorder: '#ededee',
      subtleForeground: referenceColors.neutral.gray['2a60'],
      disabled: referenceColors.neutral.gray[6],
    },
    ghost: {
      background: 'transparent',
      backgroundHover: referenceColors.brand.blue[1],
      backgroundActive: referenceColors.brand.blue[2],
      border: 'transparent',
      borderHover: referenceColors.brand.blue[3],
      borderActive: referenceColors.brand.blue[3],
      foreground: referenceColors.brand.blue[8],
      subtleBackground: referenceColors.brand.blue[1],
      subtleBorder: referenceColors.brand.blue[3],
      subtleForeground: referenceColors.brand.blue[8],
      disabled: referenceColors.neutral.gray[6],
    },
  },
} as const;

export const colors = {
  reference: referenceColors,
  semantic: semanticColors,
} as const;
